---
- name: enable firewall with handler
  hosts: all
  become: true
  tasks:
    - name: enable firewall
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
      notify:
        - reload firewalld

  handlers:
    - name: reload firewalld
      service: 
        name: firewalld
        state: reloaded
